Naval-Base/yuudachi

package.json, src/bot/commands/docs/mdn.js, src/bot/commands/docs/npm.js
Adds MDN and NPM search commands.
=> feat: add MDN and NPM search commands

src/bot/commands/docs/docs.js
=> Add force fetching capability to docs

package.json, src/bot/commands/info/emoji.js, yarn.lock
Adds some utility for fetching data about guild and built-in emojis. Mostly useful for getting raw representations of built-in emojis for use in scripts.
P.S. Also made it possible to start the bot on systems without build tools.
=> feat(Commands): add emoji info command

package.json, src/bot/client/YukikazeClient.js, src/bot/commands/reminders/add.js, src/bot/commands/reminders/delete.js, src/bot/commands/reminders/list.js, src/bot/commands/reminders/reminder.js, src/bot/models/reminders.js, src/bot/structures/Database.js, src/bot/structures/Scheduler.js, src/bot/util/Util.js, src/yukikaze.js, yarn.lock
Addition of the ability to create reminders, list reminders, and delete reminders.
=> Feat: reminders

src/bot/commands/info/emoji.ts, src/bot/commands/mod/case.ts
this pr fixes an issue with the case command when the called case is a mute and changed regex to support animated emojis
=> support animated emojis & date problem in case.js

src/bot/commands/docs/docs.ts
- doc support bump to 11.5-dev
- remove 11.4-dev as the branch has been deleted
=> doc support bump to 11.5-dev

src/bot/commands/config/toggle.ts, src/bot/commands/config/tokenFiltering.ts, src/bot/listeners/client/messageDelete.ts, src/bot/listeners/client/messageTokenFiltering.ts, src/bot/listeners/client/messageUpdate.ts, src/bot/package.json
And ignore a few listeners in DMs. Nothing big
=> src: Add token filtering

src/bot/commands/reminders/add.ts
=> fix: clean reminder reason

src/bot/package.json, yarn.lock
Reverts Naval-Base/yukikaze#504
=> fix: revert "chore(deps): bump winston-daily-rotate-file from 4.1.0 to 4.2.0"

src/bot/commands/tags/edit.ts, src/bot/util/constants.ts
When prompting and for the reply message.
=> fix: edit not taking template flags into account

babel.config.js, docker-compose.local.yml, docker-compose.prod.yml, docker-compose.yml, docker/packages/handler/Dockerfile, jest.config.js, package.json, packages/api/package.json, packages/api/src/Route.test.ts, packages/api/src/Route.ts, packages/api/src/app.test.ts, packages/api/src/app.ts, packages/api/src/managers/CaseLogManager.ts, packages/api/src/middleware/authorize.ts, packages/api/src/routes/guilds/[guildId]/cases/post.test.ts, packages/api/src/routes/guilds/[guildId]/cases/post.ts, packages/api/src/routes/hasura/actions/post.ts, packages/api/src/routes/hasura/hooks/post.ts, packages/handler/bin/index.ts, packages/handler/package.json, packages/handler/src/Command.test.ts, packages/handler/src/Command.ts, packages/handler/src/commands/util/ping.ts, packages/handler/src/tokens.ts, packages/handler/src/types/broker.ts, packages/handler/tsconfig.eslint.json, packages/handler/tsconfig.json, pnpm-lock.yaml
~~No tests yet, will be doing later.~~
=> feat(handler): Implement handler

.gitignore, docker-compose.config.example.yml, docker-compose.local.yml, docker-compose.prod.yml, docker-compose.yml, y.ps1
- Title
- Move some constant values (mostly endpoints) into the base Docker Compose file since they cannot change between environments
- Add example config file so people know what they need to fill out to run the bot
=> build(docker): move sensitive configuration values into separate ignored file

.github/workflows/node.yml
Validate PRs to ensure that tests pass and coverage is up to standard.
=> ci(github): run tests on PR

README.md, docker-compose.local.yml, docker-compose.prod.yml, docker-compose.yml, docker/packages/api/Dockerfile, docker/packages/handler/Dockerfile, docker/packages/website/Dockerfile, package.json, yarn.lock
This PR changes references of `yukikaze` to `yuddachi`
=> chore: replace refernces of yukikaze to yuudachi

src/bot/commands/doc/npm.ts, src/bot/commands/info/channel.ts, src/bot/commands/info/emoji.ts, src/bot/commands/info/role.ts, src/bot/commands/info/server.ts, src/bot/commands/info/user.ts, src/bot/commands/tag/info.ts, src/bot/listeners/client/guildLog/messageDeleteBulk.ts, src/bot/listeners/client/memberLog/guildMemberAdd.ts, src/bot/listeners/client/memberLog/guildMemberRemove.ts, src/bot/package-lock.json, src/bot/util/constants.ts
- use a central constant for date formats across the project
- add missing formatting string for member logs
=> chore(constants): use central date format

src/bot/listeners/client/guildLog/messageDelete.ts
Improve message logging
- log messages without content
- log amount of embeds if no content
- log all attachments instead of just the first
=> feat(logs): log messages without content, log multiple attachments

src/bot/commands/mod/multiban.ts, src/bot/commands/util/cybernuke.ts, src/bot/listeners/client/memberLog/guildMemberAdd.ts, src/bot/listeners/client/memberLog/guildMemberRemove.ts, src/bot/structures/CaseHandler.ts, src/bot/util/constants.ts
- chore(multiban): prevent reply editing
- chore(cybernuke): prevent reply editing
- feat(cybernuke): improve ux
* add current time as reference
* make time stand out
* use global format constant
- chore(logs): consistency in date display
- chore(cases): guard intrusive user names with code
- fix(*): use 24h time format
=> feat(*): ux improvements

src/bot/commands/util/cybernuke.ts, src/bot/listeners/client/memberLog/guildMemberAdd.ts, src/bot/listeners/client/memberLog/guildMemberRemove.ts
The method obviously needs to be called
=> fix(cybernuke): regression from #792

src/bot/inhibitors/sendPermissions.ts
This PR adds an inhibitor that will check if client has permissions to send messages in message channel.
Not sure if this is everything that's needed for it to work, but can edit later on.
=> feat: add send permissions inhibitor

src/bot/commands/mod/multiban.ts, src/bot/commands/util/cybernuke.ts
- member fetch in before option so members are being resolved correctly
- remove need for Guild#member to stay compliant with new discord.js features
=> fix(*): use before for member resolving

src/website/src/components/GuildCases.tsx, src/website/src/components/GuildTags.tsx, src/website/src/components/Table.tsx, src/website/src/components/modals/GuildTag.tsx, src/website/tsconfig.json
=> feat(website): refresh table | action string on table

docker-compose.local.yml, docker-compose.prod.yml, packages/api/src/api/Users.ts, packages/api/src/index.ts, src/api/src/managers/CaseLogManager.ts, src/api/src/routes/users/[userId]/get.ts, src/graphql/src/resolvers/index.ts, src/graphql/src/resolvers/query/user.ts, src/graphql/src/typeDefs.ts, src/handler/src/commands/moderation/restrict.ts, src/website/src/Constants.ts, src/website/src/components/GuildCase.tsx, src/website/src/components/GuildCaseReference.tsx, src/website/src/components/GuildCases.tsx, src/website/src/components/modals/GuildCase.tsx, src/website/src/hooks/useMutationUpdateGuildCase.ts, src/website/src/hooks/useQueryGuildCase.ts, src/website/src/hooks/useQueryMe.ts, src/website/src/hooks/useQueryUser.ts, src/website/src/interfaces/GuildCases.ts, src/website/src/interfaces/User.ts
closes #879
closes #880
closes #884
closes #885
closes #898
=> feat(website,api,graphql): case viewing/editing

src/events/guild-log/messageDelete.ts, src/events/guild-log/messageDeleteBulk.ts, src/events/guild-log/messageUpdate.ts, src/events/guild-log/voiceStateUpdate.ts, src/functions/logs/generateCaseLog.ts, src/functions/logs/upsertCaseLog.ts
Followed Tai's color palette (with the exception of voiceStateUpdate):
=> feat: Add embed colors to guild/case logs.

locales/en-US/translation.json, package-lock.json, package.json, src/commands/moderation/anti-raid-nuke.ts, src/interactions/moderation/anti-raid-nuke.ts, src/util/generateTargetInofrmation.ts
- QoL: move nuke formatting into a util function
- Show the range of possible target join and creation date (within x minutes/days)
- Allow pattern filter (RE2), split pattern string into multiple i18n strings
- Default deletion to 1 day, this is a command to combat spam, afterall
=> feat(anti-raid-nuke): pattern filter

src/functions/anti-scam/checkScam.ts, src/util/resolveRedirect.ts
- More sophisticated link checks via continually consumed regex.
- Following redirects to still detect shortened scam domains.
=> feat(antiscam): resolve redirects

src/events/guild-log/messageDeleteBulk.ts
Fixes a regression from ignore channels causing a return for bulk deletes inside a guild (the opposite is wanted)
=> fix(logs): log bulk delete in guilds

src/events/anti-scam/messageCreate.ts, src/events/anti-spam/messageCreate.ts
Consider discord native automod when handling scams and spam
=> feat(automod): support discord native automod

.vscode/settings.json, locales/en-US/translation.json, package.json, src/events/guild-log/messageDelete.ts, src/events/guild-log/messageDeleteBulk.ts, src/events/guild-log/threadCreate.ts, src/events/guild-log/threadDelete.ts, src/index.ts
- Log stickers
- Allow ignoring based on any level of channel nesting
- Make attachment string i18n
- Log thread delete and create (if newly created)
=> feat(logging): log improvements

src/interactions/ArgumentsOf.ts, src/interactions/InteractionOptions.ts
- fix: mentionable should not include channels
- support attachment options in command handler
=> feat(commands): support attachment option

migrations/1658336153-rolefilters.js, src/events/anti-scam/messageCreate.ts, src/events/anti-spam/messageCreate.ts, src/functions/settings/getGuildSetting.ts
=> feat(automod): support ignoring roles

packages/yuudachi/locales/en-US/translation.json, packages/yuudachi/src/events/guild-log/messageDelete.ts, packages/yuudachi/src/events/guild-log/messageDeleteBulk.ts, packages/yuudachi/src/events/guild-log/messageUpdate.ts
> **Note**
> closes #1074
- Log replies in delete events (with message id, author tag, author id, message jump link, mention indicator)
- Refactor to easier-to-understand parts arrays
- Resolve TODO to ignore thread parent categories
```
[2022/07/30 23:50:12 (UTC)] Souji#0001 (83886770768314368): mention off
↳ Replying to 1003073081130102845 (https://discord.com/channels/883776715061620826/984143958219325550/1003073081130102845) by Groverrr#8652 (175179625880616960)
[2022/07/30 23:50:08 (UTC)] Souji#0001 (83886770768314368): mention on
↳ @Replying to 1003073081130102845 (https://discord.com/channels/883776715061620826/984143958219325550/1003073081130102845) by Groverrr#8652 (175179625880616960)
```
=> feat(logs): log replies in message deletions

packages/yuudachi/src/functions/anti-raid/blastOff.ts
chore(error): improve error handling on case failing
=> fix(anti-raid): do not create case on dry-run

packages/yuudachi/package.json, packages/yuudachi/src/events/interactionCreate.ts
Sometimes you just gotta know when to stop.
It's enough.
Let it go.
=> feat(*): prevent crash from error handling

packages/yuudachi/locales/en-US/translation.json
- Consolidate tags, if possible
- Reorder based roughly on historical experience from server moderation
=> feat(reasons): consolidate and reorder based on use

packages/yuudachi/src/commands/moderation/duration.ts
The duration command does not set the regex key for timeouts, causing the `guildMemberUpdate` handler to detect the member update event (caused by updating the timeout value) as a manual timeout: 
---
=> fix(duration): Setting the regex key on timeout update

packages/yuudachi/src/functions/anti-spam/totalMentions.ts, packages/yuudachi/src/util/codeBlock.ts
This addresses the issue of people being banned by posting mention like content inside code blocks, although the native Auto-Mod will still block the message the user won't get banned by Yuu
> Closes #1128
=> fix(totalMentions): Ignore mentions on codeBlocks

packages/framework/src/components/button.ts
=> fix(framework): allow emojis in button util

packages/framework/src/util/embed.ts
=> fix(framework): pass other embed field values to truncated field

packages/yuudachi/src/commands/moderation/reference.ts, packages/yuudachi/src/websocket/WebSocketConnection.ts
=> fix(cases): reference case

packages/yuudachi/src/websocket/WebSocketConnection.ts
=> fix(ws): logging back-off properly

.github/workflows/tests.yml, docker-compose.local.yml
Because tests are good, Yay
This adds unit tests for `prod` and `local` and fixes a typo in the prometheus image
=> feat(tests): add tests to docker images

packages/yuudachi/src/Constants.ts, packages/yuudachi/src/functions/cases/createCase.ts, packages/yuudachi/src/interactions/moderation/unban.ts
> **Warning**
> This PR requires a command re-deploy
=> fix(reports): ignore `Timeout End` and `Unban` for Auto-Resolve

packages/yuudachi/src/events/interactionCreate.ts
Reverts part of d52303404a6e81e291d12c6b557a928610d1b956
*Sorry Souji*
=> fix(interactions): error handler of the error handler

apps/yuudachi/src/events/anti-scam/messageCreate.ts, apps/yuudachi/src/events/guild-log/voiceStateUpdate.ts, apps/yuudachi/src/events/manual-ban/guildBanAdd.ts, apps/yuudachi/src/events/manual-ban/guildBanRemove.ts, apps/yuudachi/src/events/manual-kick/guildMemberRemove.ts, apps/yuudachi/src/events/manual-report-status/threadUpdate.ts, apps/yuudachi/src/events/manual-timeout/autoModerationActionExecute.ts, apps/yuudachi/src/events/manual-timeout/guildMemberUpdate.ts, apps/yuudachi/src/events/readyOnce.ts, apps/yuudachi/src/events/role-assignment/guildMemberAdd.ts, apps/yuudachi/src/index.ts
* fix bug that prevented leave logs
* fix bug that caused logging from ignored to ignored
* clarify dependencies based on event type
* add logger for case of channel updates
* pull ignore logic into separate constants
* increase voice state cache due to recent rise in voice trolling
> [!NOTE]  
> Modifies client settings
=> refactor(logs): voice state logging
