Naval-Base/yuudachi

src/bot/commands/docs/mdn.ts

This is a simple change using `String#replace` to reverse the `<code>` and `<strong>` elements of MDN summaries in order to properly display them in Markdown when passed through Turndown. It'll stop `**this syntax**` and make it the **`prettier version`**.

Fix code and strong elements in MDN summary being backwards.

---

src/bot/commands/info/emoji.ts

Some ucs2 decoded, hex encoded characters are only 2 characters long. This ensures that they get padded with 0's in order to be valid Unicode escape sequences.

fix(Emoji): Unicode escape sequences

---

src/bot/commands/info/emoji.ts

`EMOJI_REGEX` from #243 was capturing the 'a' for animated emojis and the emoji's name which changed 
the offset of the emoji id's index in the array, this PR fixes that and also attempts to find the emoji by name to reflect the examples.

fix(emoji): Emoji regex & support for finding emoji by name

---

src/bot/commands/docs/docs.ts

~~Some versions do not have aliases set by the docs API so the URL to the libraries JSON docs file has to be  provided to the query.   
This PR support for these discord.js versions.~~
Edit: only includes 11.4-dev after feedback

Include 11.4-dev in docs command

---

src/api/index.ts
src/api/package.json
src/bot/client/YukikazeClient.ts
src/bot/package.json
yarn.lock

And fixed all the breaking changes I could find, I don't know how to properly test this repository, so all honesty, this is untested.

chore(deps): Bump veza from 0.5.0 to 0.6.0

---

src/bot/commands/reminders/add.ts

Earl Grey tea is best enjoyed at 3-4 minutes to avoid bitterness.
Previously i had to slightly over-steep my beloved tea due to the 5 minute minimum timer

Reduce minimum timer to 3m

---

src/bot/commands/config/config.ts
src/bot/commands/config/delete.ts
src/bot/commands/config/set-restrict.ts
src/bot/commands/config/set.ts
src/bot/commands/config/toggle.ts
src/bot/commands/mod/ban.ts
src/bot/commands/mod/cases.ts
src/bot/commands/mod/embed.ts
src/bot/commands/mod/emoji.ts
src/bot/commands/mod/kick.ts
src/bot/commands/mod/mute.ts
src/bot/commands/mod/reaction.ts
src/bot/commands/mod/restrict.ts
src/bot/commands/mod/softban.ts
src/bot/commands/mod/tag.ts
src/bot/commands/mod/unban.ts
src/bot/commands/mod/warn.ts
src/bot/commands/reminders/reminder.ts
src/bot/commands/tags/tag.ts
src/bot/commands/util/help.ts
src/bot/commands/util/prefix.ts
src/bot/listeners/client/guildBanAdd.ts
src/bot/listeners/client/guildBanRemove.ts
src/bot/listeners/client/guildMemberUpdate.ts

Still uses `as`, which  isn't great. If you want me to do a refactor or something to remove this unsafe casting then tell me. It's better than ts-ignore though.

Remove unnecessary ts-ignores 

---

src/bot/commands/tags/add.ts
src/bot/commands/tags/edit.ts
src/bot/commands/tags/show.ts
src/bot/util/template.ts
src/bot/util/templateParser.ts

This adds the ability to do templating for tags. The proposed syntax for interpolation is the following:
- `${ var }` interpolates the preset value of `var`, this can be like `author` or `channel`.
- ~~`${ 0 }` interpolates an argument variable, the idea is that you can do `?tag | arg0 arg1 etc`.~~
- `${ x | y | z }` interpolates the first existing variable.
- `${ x | y | z = "default" }` interpolates the first variable that exists, or the default. You can nest templates inside the default string.
Of course, you can use any combination of these features.  
Valid identifiers are `/^[A-Za-z0-9]+$/`, but we can add other characters if it looks nice.  
You can escape with a `\` to insert a literal `${`, `"`, or `\`.  
As for the commands, we should have a flag that switches to templating mode …

[WIP] Add templating to tags

---

src/bot/listeners/client/guildLog/messageDelete.ts
src/bot/listeners/client/guildLog/messageDeleteBulk.ts

* add jumplink to messageDelete (while the message might be deleted already this still allows to jump to the closest message in said channel, which can be important to find the context of the deleted message)
* add channel to messageDeleteBulk (bulkDelete emits once per channel, thus the channel can be provided as information based on the first - or really any - message in the collection)
Format should be consistent with other events.

feat: additional log information

---

src/bot/commands/doc/docs.ts

This PR fixes the help command examples of the command, where the correct usage to access another branch other than stable is ``--src=branch``.

fix: Update the help command of docs

---

src/bot/structures/LockdownScheduler.ts

This PR also denies `ADD_REACTIONS` when locking down a channel using the `lockdown` command.
Since the first thing people do once they notice that they can no longer send messages is spamming reactions, this would be a good way to counter that.
---
Is it intended to explicitly set the permissions to `true` on the overwrite after lifting the lockdown?
I'd assume the everyone role would have that (or these) permission(s) per default and setting it to `inherit` / `null` could be preferred.

feat(lockdown): deny ADD_REACTIONS permission

---

src/bot/commands/doc/docs.ts

This PR removes the `11.5-dev` docs source from the `docs` command and adds `v11` as replacement.
The `11.5-dev` branch is no longer and should not be referenced any more and `v11` would be the """current""" counterpart.

refactor(docs): replace 11.5-dev source with v11

---

src/bot/commands/info/channel.ts

There's a missing colon in the `channel` command, so this pull request puts it in its place!

fix(info.channel): missing colon

---

hasura/migrations/1586479065565_next/down.sql
hasura/migrations/1586479065565_next/up.sql
hasura/optional_migrations/1586479065565_next/down.sql
hasura/optional_migrations/1586479065565_next/up.sql
packages/api/src/managers/CaseLogManager.test.ts
packages/api/src/managers/CaseManager.test.ts
packages/api/src/managers/CaseManager.ts
packages/api/src/managers/SettingsManager.test.ts
packages/api/src/managers/SettingsManager.ts
packages/parser/bin/index.ts

There is deliberately no migration for actions in the `down.sql` because it's a destructive up migration that simply cannot be reverted without keeping state somewhere. This is a non-issue for us though.
This also fixes the reason in the audit log to be somewhat consistent with the current implementation:
It would be odd to have a very long reason in there which gets cut off by Discord putting an ellipses there, so I decided to opt for just the case itself.

refactor(db): rewrite migrations for cases and settings

---

.dockerignore
docker-compose.local.yml
docker-compose.yml
docker/packages/api/Dockerfile
docker/packages/handler/Dockerfile
docker/packages/parser/Dockerfile
docker/postgresql/Dockerfile
hasura/metadata/tables.yaml
hasura/optional_migrations/1586479065565_next/up.sql
jest.config.js
package.json
packages/api/bin/index.ts
packages/api/package.json
packages/api/src/managers/CaseLogManager.test.ts
packages/api/src/managers/CaseLogManager.ts
packages/api/src/managers/CaseManager.test.ts
packages/api/src/managers/CaseManager.ts
packages/handler/bin/index.ts
packages/handler/package.json
packages/handler/src/commands/util/ping.ts
packages/parser/bin/index.ts
packages/parser/package.json
packages/rest/package.json
packages/rest/src/Rest.test.ts
packages/rest/src/Rest.ts
packages/rest/src/index.ts
packages/rest/tsconfig.eslint.json
packages/rest/tsconfig.json
pnpm-lock.yaml

- Removes spectacles/rest in favor of spectacles/proxy
- Some minor fixes
- Resolved issues with `pnpm` not being executable after installation using `npx`
- Fixed errors with Hasura configuration and optional migrations
- Fixed port binding conflict between API and Grafana by re-binding the API to port 4000

Add Discord data proxy for REST

---

y.ps1

Makes launching the bot easier. `.\y [env] [...docker command]`: for example, `.\y local up --build`.

chore: add simple launch script for Windows

---

src/handler/Constants.ts
src/handler/util/index.test.ts
src/handler/util/index.ts

Add embed utilities for handler
* ellipsis: truncate string input with `...` if applicable
* addField: immutably add a field to the provided embed structure
* truncateEmbed: truncate embed attributes as appropriate
`truncateEmbed` is especially useful to construct embeds from external api responses as well as i18n input. Instead of having to truncate each attribute and apply the logic in each command this centralizes the logic into a tested utility function and allows a single call before sending the embed, resulting in much cleaner command code, where applicable.
**caveat**: in case of upstream API changes constants need to be adapted.

feat(handler): embed utils

---

src/handler/bin/index.ts
src/handler/src/Command.ts

This PR aims to introduce the ability for commands to be executed via regular expressions.
- Command: new optional regExp property which can hold a regular expression, the command can be triggered with. The positional args are retrieved from the capture groups
- Command#execute has a new argument with the execution context (enum, so far prefixed and regexp, other - like web - are thinkable) allowing for context-aware execution of commands (silent fails on regex commands to not disturb conversations if args are only later found to be unusable for this command, due to accidental matching.
- Command: consumes the Args instance as it would with other commands, flags and options are omitted, UX seems to suffer once one introduces flags into pattern commands that can execute on any position in …

feat(handler): regex commands

---

src/handler/util/index.test.ts
src/handler/util/index.ts

The truncate handling introduced in #768 is not correct type-wise and prevents building the project if used.  This PR aims to fix this by introducing the correct defaulting mechanism to `undefined` instead of `null`. Additionally embed authors do not necessarily have a name, which was not handled properly before.

fix(handler): proper handling of embed types in truncate

---

src/handler/bin/index.ts

This PR filters out non-matching optional match groups during RegExp execution of commands, allowing for optional regex arguments and more variable matching patterns.
Example:
- `owner/repository#issue`
- `alias#issue`

feat(handler): allow optional match groups

---

src/bot/listeners/client/memberLog/guildMemberAdd.ts
src/bot/listeners/client/memberLog/guildMemberRemove.ts

- #joinedAt and #joinedTimestamp are nullable because discord actually just provides a User object and guild id on GUILD_MEMBER_REMOVE
- should the member be uncached discord.js creates a GuildMember instance from this resulting in unwanted behavior
- this PR fixes this by just providing information if it is actually available
- since the underlying User object will always be valid there is no need to apply the same checks for user properties like the account creation date

fix(logs): only provide information if available

---

src/bot/commands/mod/antiraid.ts
src/bot/listeners/client/moderation/guildMemberAdd.ts
src/bot/util/constants.ts

Add capability to lock down a guild based on provided action (kick/ban) and minimum account age.
1. command `?antiraid <kick|ban> <age> | <disable>`
1. guildMemberAdd listener to independently evaluate joins in the moderation category 
1. antiraid log color to easily discern cases regarding automod
PR is untested (as hasura hates me)

feat: add antiraid functionality

---

src/bot/commands/mod/ban.ts
src/bot/commands/mod/softban.ts

- Softban, ban, cybernuke and about to be added multiban should not differ in default usage
- 1 day is feasible, the chances that people hit by destructive actions go more than one day undetected is very low (for these cases the flag can still be specified).
- bounds handling: min days is 0 (no messages deleted) max days is 7

chore: consistent day defaulting and bounds

---

src/bot/commands/util/cybernuke.ts
src/bot/util/constants.ts

- take input in ms format `1d`, `1h`, `2m`, `20s` etc. rather than raw milliseconds
- provide feedback to the user what the chosen cutoff dates are so they can adjust the parameters in the next attempt
- add `-r`, `--report` flag to return a .txt file with all successfully banned user IDs separated by newline, for easier T&S reporting
- ignore answers that are not y,yes,n,no
- streamline response with new multiban command
- add appeal address to cybernuke target notification
- add executor and counter to reason

feat(cybernuke): improve verbosity and ux

---

src/bot/commands/mod/multiban.ts
src/bot/util/constants.ts

Adds a feature to ban multiple members in one go.
- checks current bans, hierarchy, currently managed users and validates global user ids
- filters and still allows a ban as long as a single valid user was provided
- asks for confirmation and provides insight on how many were filtered for what reason
- bans the valid members.
- `-r`, `--report` flag to return a .txt file with all successfully banned user IDs separated by newline, for easier T&S reporting

feat: multi ban command

---

src/bot/listeners/client/moderation/guildMemberAdd.ts
src/bot/util/constants.ts

Rework antiraid, this time it hopefully actually does things instead of just logging them. The Action utility can't be used due to its dependence on a message, which is not available for automated on-join bans. PR is untested

fix(antiraid): rework to execute actions

---

src/bot/commands/info/user.ts
src/bot/commands/mod/antiraid.ts
src/bot/commands/mod/cases/show.ts
src/bot/commands/mod/history.ts
src/bot/commands/mod/multiban.ts
src/bot/commands/tag/info.ts
src/bot/commands/util/cybernuke.ts
src/bot/listeners/client/moderation/guildMemberAdd.ts
src/bot/structures/CaseHandler.ts
src/bot/structures/case/actions/Action.ts
src/bot/structures/case/actions/Ban.ts
src/bot/util/constants.ts
src/bot/util/graphQL.ts

- Improvements on various commands, streamlining embed designs
- escaping userinput with inline codeblocks where possible, to prevent it from growing out of the embeds boundaries if zalgo or other vertically or horizontally challenging characters are used
- userinfo: fetches members if needed and works with non-members
- history: now actually useful, restricted to moderation role only
- multiban and cybernuke now available with log setting nsfw
- cybernuke: add flag to list targets before execution
- use typing indicators for bulk commands instead of updating messages, split and send long member lists
- unify date formatting
- reminder that https://github.com/Naval-Base/yuudachi/pull/750 is still open
muterole-rolestate conflict: need to keep an eye on that one, as it's entirely not …

feat(*): various qol features

---

src/events/manual-ban/guildBanRemove.ts
src/functions/cases/deleteCase.ts

While an unban reason cannot be provided in the GUI, other bots might be able to. Currently, the reason retrieved from the audit log (if present) is ignored. 
This PR fixes this by passing the audit log reason to `deleteCase`.

fix(unban): respect reason on manual unban

---

locales/en-US/translation.json
src/commands/moderation/reason.ts
src/interactions/moderation/reason.ts
src/util/embed.ts

* Allow reason slash command to (optionally) take a "last case" option for bulk setting case reasons
* Reject if first or last case is invalid
* Require confirmation flow in case of range (no confirmation for single case)
* Supply information about the amount of failed attempts in success message in case of range
---
* `truncate` utility (contrary to ellipsis this takes split characters into consideration and only adds chunks up to the next split character to the result. this is preferable here to not apply an ellipsis mid-link formatting and break escapes)
---
| ℹ️  Due to the nature of slash command argument order the optional last case has to sit behind the reason, causing somewhat unintuitive command usage. This could be prevented by splitting the command into sub-commands, however, I …

feat(reason) allow optional range

---

src/commands/moderation/anti-raid-nuke.ts

Anti-Raid-Nuke currently falls back to `Anti-Raid-Nuke hit {{- members}} guild members.` as a reason in the log embed, if no reason is supplied to the command. This PR adds the count of fatalities as the `members` parameter to properly display hit count, as expected.
current behavior with missing fatality count:

fix(nuke): member count in log embed

---

locales/en-US/translation.json
src/events/guild-log/messageDelete.ts
src/events/guild-log/messageDeleteBulk.ts

- Fix contentless messages not getting the "No content" description (content is empty string, not nullish)
- Change the bulk delete symbol to an arrow to more clearly associate attachments with the message they belong to
- Add attachment logs to single message delete guild logs (useful to access deleted files shortly after deletion for moderation purposes) (deliberate decision against re-uploading the file to prevent accidental redistribution of content)

feat: log attachment proxy on single msg delete

---

src/events/interactionCreate.ts

Using the iterator loop causes a pending command (awaiting input via buttons) to block any further commands. Since these are stuck in the iteration we don't reply within 3s causing the interaction to fail. Awaiting the command execution is, however, required to properly handle errors.
This PR fixes this by switching the `interactionCreate` event handler to use the regular node event loop instead. This prevents requests from blocking.

fix(interactionCreate): use event instead of async iterator loop

---

src/commands/moderation/lockdown.ts
src/commands/moderation/sub/lockdown/lift.ts
src/commands/moderation/sub/lockdown/lock.ts
src/functions/lockdowns/createLockdown.ts
src/interactions/moderation/lockdown.ts

- fix i18n strings to correctly specify `.errors` in the path
- return early if the permissions to create overwrites are missing
- deny permissions regarding threads on lockdown
- add overwrite so the bot is able to send lockdown messages without administrator permissions
- QoL: narrow text channel type allowed for lockdown command to `GUILD_TEXT`

fix(lockdown): permissions

---

src/Constants.ts
src/events/anti-scam/messageCreate.ts
src/events/anti-spam/messageCreate.ts
src/functions/anti-scam/checkScam.ts
src/functions/anti-scam/totalScam.ts

- Disconnect scam checks from spam counter
- Use scam counter with reset timer to check for scams
- Optimize lowercasing of comparison string
- One unique increase per message, no matter how many scam domains (scenario: user listing scam domains to report, gets banned because the threshold is exceeded)

feat(scams): use scam counter disconnected from spam checks

---

locales/en-US/translation.json
src/commands/utility/checkScam.ts
src/commands/utility/refreshscams.ts
src/deploy.ts
src/interactions/index.ts
src/interactions/utility/checkScam.ts
src/interactions/utility/refreshscams.ts
src/jobs/scamDomainUpdateTimers.ts

- add command to manually check strings against known domains, providing information (amount of known domains, last update) in the response
- add command to manually refresh scam domains (option to delete the cache to get rid of false flags, if necessary)

feat(antiscam): debug commands

---

src/util/generateHistory.ts

This fixes a bug where long descriptions for case history that need to be truncated do not show the truncated history due to a mismatch of the provided `summary_truncated` and expected `summary` key in i18n.

fix(history): correct key for i18n string replace

---

src/commands/utility/checkScam.ts
src/commands/utility/refreshscams.ts
src/interactions/utility/checkScam.ts
src/interactions/utility/refreshscams.ts

The antiscam debug commands introduced in #1022 should be permission locked to prevent abuse and because they should generally not be used by regular users to potentially scope validation
⚠️ This PR requires a command re-deploy

fix(antiscam): debug commands should be mod locked

---

src/Constants.ts

Tests have shown that yuudachi missing scams seems to be predominantly caused by the compromised account drip-feeding messages with longer breaks, exceeding the current scam timeout.
This PR addresses this ongoing issue by adapting various constants to be much stricter in order to prevent slower spam and scam attempts.

chore(constants): adapt thresholds and expire timers

---

src/interactions/moderation/lockdown.ts

As per documentation <https://discord.com/developers/docs/interactions/application-commands> `channel_types` has to be an array. This restriction is currently ignored, because a number is provided, offering non-text channels for selection.

fix(lockdown): channel_types has to be array

---

src/util/generateHistory.ts

The change to log timeout expiration has made the handling of this case type in history generation necessary. The initial PR has not covered this case, resulting in a command error when pulling the history of a user that has been timed out before.
- empty fallback analogue to unrole
- ignore in history to not clutter the list analogue to unrole

fix(timeouts): handle history for timeouts

---

src/functions/anti-scam/checkScam.ts

We know of a scam domain called `discordapp.co`, making legit discord CDN links to `discordapp.com` trip under the current system. This proposal fixes this specific issue and makes our approach more robust against other types of false positives.
- use the native `URL` class as parser to extract host (including subdomain)
- use `#endsWith` to be robust against subdomain evasion
- prefix both the host of the domain as well as the scam host with `.` to prevent substrings from tripping (e.g. `idscord.com` would fail with just `#endsWith`)
- use a stricter regular expression, so only embedded links trip the regex (preventing us from checking and redirect-fetching `a.b.` or similar from conversations centered around code)
**Addressing Reviews:**
- I did not implement the proposal to split by …

fix(antiscam): improve robustness against false positives

---

src/events/anti-scam/messageCreate.ts
src/events/anti-spam/messageCreate.ts
src/functions/anti-spam/totalContents.ts

If the user writes a message on the server (not containing scam domains) after being banned and unbanned for a false positive scam attempt flag, the user is immediately re-banned, because the key still exists and is checked on the new message.
This PR attempts to remove this issue by deleting the respective redis keys after a ban/softban for exceeding scam/ban thresholds.
- To facilitate this change I also make the creation of the hash key a reusable utility function, to be consistent across context

fix(scamspam): delete keys to prevent re-action after false positive unban

---

locales/en-US/translation.json

To grammatically make sense, the `in` is redundant, as it's already included in native Discord timestamps, if the timestamp is in the future.

chore(lockdown): change sentence structure to fit timestamp layout

---

locales/en-US/translation.json
src/commands/moderation/lockdown.ts
src/commands/moderation/sub/lockdown/lock.ts
src/functions/lockdowns/deleteLockdown.ts
src/jobs/modLockdownTimers.ts

- use reason in the public-facing message, omit completely if no reason is set ("due to moderation" is not informative)
- use the proper JobType key, which caused the lockdown to error on lift attempt
- resolve the case even if the lifting errors (this used to cause errors on every job cycle, because of missing permissions)
- inform of missing permissions if the bot is not an administrator
Note: The bot requires the `ADMINISTRATOR` permission to use lockdown, this is due to Discord not allowing bots to set the `MANAGE_ROLES` permission, if the user is not an administrator. This causes issues with the way lockdowns work (removing overwrites, saving them, and setting them in place again after the lockdown duration is over).

feat(lockdowns): reason, error prevention

---

migrations/1625779687-logfilters.js
src/events/guild-log/messageDelete.ts
src/events/guild-log/messageDeleteBulk.ts
src/events/guild-log/messageUpdate.ts
src/events/guild-log/voiceStateUpdate.ts
src/functions/settings/getGuildSetting.ts

Proposal to introduce the ability to ignore channels via guild settings
- joins into ignored channels are ignored
- moves into ignored channels are logged as a leave of the previous channel
- moves out of ignored channels are logged as a join of the new channel
- leaves out of ignored channels are ignored
- are ignored via ID
- ignore via category channel will be added at a later date, once the code base is updated to the point where `#inGuild` is available. Checking for guild-based channels is currently a massive hassle.
- are ignored via ID
- are ignored if the parent is ignored

feat(logs): ignore channels via guild settings

---

src/functions/anti-scam/checkScam.ts
src/jobs.ts
src/jobs/discordScamDomainUpdateTimers.ts

Use the bad domain list the Discord client pulls as a secondary resource to determine scam domains, if the phish project did not produce a hit.
⚠️ This requires a new environment variable `SCAM_DOMAIN_DISCORD_URL`

feat(antiscam): use discord bad domains as secondary scam domain check

---

locales/en-US/translation.json
src/commands/moderation/anti-raid-nuke.ts
src/interactions/moderation/anti-raid-nuke.ts

We have experienced raiders before that were drip-fed into the server over months, then all changed their avatars and stared to DM-spam members. This PR adds the ability to filter for avatar hash (global and guild-based) matches in the anti raid nuke command.
⚠️ this requires re-deploying commands, because an option was added to "anti-raid-nuke"

feat(anti-raid-nuke): allow filtering by avatar hash

---

src/functions/lockdowns/deleteLockdown.ts

If a channel is deleted before the lockdown is resolved, the current setup causes errors on each check cycle, due to failure of channel fetching. 
This PR attempts to fix this by including the fetching in the try body and resolving the lockdown regardless.

fix(lockdown): handle deleted target channel

---

locales/en-US/translation.json
src/commands/moderation/softban.ts

- No longer throw if the member is not on the guild anymore
- Update the prompt to reflect that the member is no longer on the guild, if applicable
- Do not generate a case if the member is not on the guild
- Update success messages with a branch for the clearing action
This setup serves two purposes:
1. Alert the moderator issuing a softban that the member is already gone (potentially to dodge the hammer, potentially because someone else already actioned them), allowing them to cancel out and re-assess the situation
2. Allow clearing messages of people that have left the server already/have been kicked or banned without specifying the `days` option by accident
A nice side-effect is no longer getting "missing permissions" when that was not the case to begin with (`.bannable` failed …

feat(softban): allow non-members to be softbanned

---

src/Constants.ts
src/commands/moderation/case.ts

- Prepend rather than append
- Only add to unique map, if the entry does not exist yet, ensuring that the newer tags are used
- remove obsolete try/catch back from attempts at user validation (cannot apply, 30s global cooldown is too much for the rapid 3s autocomplete response time)

feat(case): prepend special entry

---

src/Constants.ts
src/events/anti-scam/messageCreate.ts
src/events/anti-spam/messageCreate.ts
src/functions/anti-spam/considerableText.ts

- Refactor content retrieval into own util function
- Automod: only consider blocked, not flagged messages, prevent double-counting for anti-spam and -scam measures.
- fixes #1059

fix(antispam): only consider blocked, not flagged automod messages

---

src/Constants.ts
src/commands/moderation/case.ts

- Autocomplete choices have a max name length of 100
- If long reasons were included in the looked up cases, the command would fail because the max length was exceeded
- Truncate case choice values with the ellipsis util function
- Rename old constant for consistency
- Truncate embeds before sending

fix(case): truncate choices and embeds

---

src/websocket/WebSocketConnection.ts

This should solve the issues with ws errors crashing the bot by attaching a listener to the `error` event.

fix(ws): attach error listener

---

packages/yuudachi/src/functions/anti-raid/filters.ts

The command option summary `• Avatar hash (user or member) matching: ` suggests that member avatars are considered, which they weren't so far. This PR changes that.

fix(antiraid): consider guild specific member avatar in avatar filter

---

packages/yuudachi/locales/en-US/translation.json
packages/yuudachi/src/Constants.ts
packages/yuudachi/src/commands/moderation/clear.ts
packages/yuudachi/src/commands/moderation/duration.ts
packages/yuudachi/src/commands/moderation/reason.ts
packages/yuudachi/src/commands/moderation/reference.ts
packages/yuudachi/src/deploy.ts
packages/yuudachi/src/events/guild-log/messageDeleteBulk.ts
packages/yuudachi/src/functions/logging/formatMessagesToAttachment.ts
packages/yuudachi/src/functions/logging/generateCaseLog.ts
packages/yuudachi/src/functions/pruning/pruneMessages.ts
packages/yuudachi/src/interactions/index.ts
packages/yuudachi/src/interactions/moderation/clear.ts
packages/yuudachi/src/util/generateHistory.ts
packages/yuudachi/src/util/generateMessageLink.ts

Introduce a command to clear messages in a provided range
- 1 message: clear up to and include this message
- 2 messages: clear in range between and including both messages
- 12h in the past max to safeguard (accidental) abuse
- Verbose confirmation flow
> **Warning**
> bulk delete logs can no longer assume a single author for all messages on bulk delete and need to be refactored to account for that
> **Note**
> Waiting for https://github.com/Naval-Base/yuudachi/pull/1080 to be merged, so this can build on the extended message logs when logging the clear as a separate action in guild logs.

feat(commands): message clear command

---

packages/yuudachi/src/util/parseRegex.ts

The full match option also needs to be respected, when net using the regex delimiter format for the pattern option

fix(anti-raid-nuke): full_match option when not using regex delimiters

---

packages/yuudachi/src/functions/anti-scam/refreshScamDomains.ts
packages/yuudachi/src/index.ts
packages/yuudachi/src/websocket/WebSocketConnection.ts

Since this bot is open source, all of the forks and local instances rely on the same `X-Identity` header which could cause issues regarding FishFish logging and abuse prevention
> **Note**
> This PR implements a new `env` variable called `SCAM_DOMAIN_IDENTITY`
> **Warning**
> **The anti-scam will refuse to connect to the WS (the WS also refuses connections without the `X-Identity` header) of fetch domain information without this env (Only discord hashes will be cached)**

chore(scam_domains): Move the `X-Identity` info to its own ENV

---

packages/yuudachi/src/functions/cases/updateCase.ts
packages/yuudachi/src/functions/reports/updateReport.ts
packages/yuudachi/src/util/object.ts

> **Note**
> I think this is the first PR that I didn't need to use this field, but why not use it anyway?
The old function is used an if the chain is combined with multiple PGs calls (including one for returning the new obj), this new approach uses objects combined with the [`SQL helpers`](https://github.com/porsager/postgres#dynamic-columns-in-updates) to provide a single and versatile DB call, while also using the `returning *` statement to return the updated object in the same call
- [Discord Thread](https://canary.discord.com/channels/222078108977594368/1018720734614392902/1018720734614392902)
- [Will initial proposal](https://github.com/Naval-Base/yuudachi/pull/1103#discussion_r947360549)
- [Based on this docs](https://github.com/porsager/postgres#dynamic-columns-in-updates)
*Sorry …

perf(update): improve update functions to only use one db call

---

packages/yuudachi/locales/en-US/translation.json
packages/yuudachi/src/util/generateHistory.ts
packages/yuudachi/src/util/generateMemberLog.ts

Add the raw timestamp values for join and creation date in member logs. Useful to better determine anti-raid-nuke arguments.
> **Note**
> Blocked while waiting for https://github.com/Naval-Base/yuudachi/pull/1103 as the user info components are refactored and made consistent

feat(memberlog): show created and joined timestamp

---

packages/yuudachi/src/interactions/moderation/anti-raid-nuke.ts
packages/yuudachi/src/interactions/moderation/unban.ts

The reasons used for quick reasons don't fit the purpose of the `Unban` and `anti-raid-nuke` commands!
> **Note**
> This PR requires a command deploy
> Closes #1126

fix(reasons): Remove autocomplete from non applicable commands

---

packages/yuudachi/locales/en-US/translation.json
packages/yuudachi/src/Constants.ts
packages/yuudachi/src/commands/moderation/ban.ts
packages/yuudachi/src/commands/moderation/kick.ts
packages/yuudachi/src/commands/moderation/lockdown.ts
packages/yuudachi/src/commands/moderation/reason.ts
packages/yuudachi/src/commands/moderation/softban.ts
packages/yuudachi/src/commands/moderation/sub/restrict/embed.ts
packages/yuudachi/src/commands/moderation/sub/restrict/emoji.ts
packages/yuudachi/src/commands/moderation/sub/restrict/react.ts
packages/yuudachi/src/commands/moderation/timeout.ts
packages/yuudachi/src/commands/moderation/unban.ts
packages/yuudachi/src/commands/moderation/warn.ts
packages/yuudachi/src/commands/utility/report.ts
packages/yuudachi/src/interactions/moderation/anti-raid-nuke.ts
packages/yuudachi/src/interactions/moderation/ban.ts
packages/yuudachi/src/interactions/moderation/kick.ts
packages/yuudachi/src/interactions/moderation/lockdown.ts
packages/yuudachi/src/interactions/moderation/reason.ts
packages/yuudachi/src/interactions/moderation/restrict.ts
packages/yuudachi/src/interactions/moderation/softban.ts
packages/yuudachi/src/interactions/moderation/timeout.ts
packages/yuudachi/src/interactions/moderation/unban.ts
packages/yuudachi/src/interactions/moderation/warn.ts
packages/yuudachi/src/interactions/utility/report.ts

Discord has an option to natively restrict string length so this PR implements the necessary changes for it
> **Note**
> This PR requires a command deployment
> **Note**
> The CI will fail because of the `yarn.lock` bug
> Closes #1131

refactor(commands): implement native string validation

---

packages/yuudachi/locales/en-US/translation.json
packages/yuudachi/src/commands/moderation/case.ts
packages/yuudachi/src/functions/logging/generateCaseEmbed.ts

This PR has effect on:
- Closes #1142 (Fixed by setting the `createdAt` field in the timestamp)
- Closes #1143 (Cases now have a button, see in `examples`)
- Bug found in testing, editing a case replaces the created timestamp (If this isn't a bug this PR would require a DB migration to implement this feature properly)
<details><summary>Examples</summary>
Case button example:
</details>

chore(case*): fix timestamp and add goto button

---

packages/yuudachi/locales/en-US/translation.json
packages/yuudachi/src/commands/moderation/clear.ts
packages/yuudachi/src/commands/moderation/sub/report/message.ts
packages/yuudachi/src/commands/moderation/sub/reports/lookup.ts
packages/yuudachi/src/commands/utility/repost.ts
packages/yuudachi/src/functions/logging/formatMessageToEmbed.ts
packages/yuudachi/src/functions/logging/upsertReportLog.ts
packages/yuudachi/src/util/createMessageLinkButton.ts

The message author link has no visuals that indicate it is a link and does not work on some mobile versions of Discord. Additionally, the semantics of associating a user name click to lead to a message link is unclear.
This PR resolves this UX issue by removing the embed author link in favor of a message component link button in all instances, where a message is resolved to an embed to display to a user.

feat(yuudachi): use message link buttons instead of embed author url

---

packages/yuudachi/locales/en-US/translation.json
packages/yuudachi/src/commands/moderation/case.ts
packages/yuudachi/src/commands/moderation/reports.ts
packages/yuudachi/src/functions/logging/generateCaseLog.ts
packages/yuudachi/src/functions/logging/generateReportLog.ts
packages/yuudachi/src/util/actionKeys.ts
packages/yuudachi/src/util/generateHistory.ts

- Add labels to case references, it's hard to know what the case referenced did without going to it, which is a pain to do repeatedly
- Refactor case system to use translations on all actions
> **Note**
>This closes #1137
<details><summary>Examples</summary>
Case log:
Reports:
</details>

chore(logs): use tranlations for actions and add the case action to the reference

---

apps/yuudachi/src/events/readyOnce.ts

- `"http://noop"` is used, because we do not care about the base name when parsing for the route.
- this is used over `req.headers.host` as it resolves with `"localhost"` in local testing, and hardcoding a `"http"` prefix would be about as gross as this approach, but this one makes it clear why it is used.

fix(metrics): use new URL API

---

apps/yuudachi/src/Constants.ts
apps/yuudachi/src/commands/moderation/sub/report/message.ts
apps/yuudachi/src/commands/moderation/sub/report/user.ts
apps/yuudachi/src/util/localizeTrustAndSafety.ts

* link to helpdesk article instead of support form (no longer used for reports)
* remove localization of support form, as it is no longer needed
resolves #1191

chore(reports): adapt discord report link
